#
# src/config/testing_subscriptions.yaml
#
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
#

defaults:
  admin_username: azureuser
  lustre_client_mount: /lustre
  lustre_oss_client_mount: /lustre/client
  msi_client_id_default: 33333333-3333-3333-3333-333333333333
  resource_groups_keep:
  - uami-rg
  subscription_default: 22222222-2222-2222-2222-222222222222
  subscription_main: 22222222-2222-2222-2222-222222222222
  tenant_id_default: 44444444-4444-4444-4444-444444444444
  vm_image_resource_group_default: image-rg
service_endpoints_default:
- service: Microsoft.AzureActiveDirectory
- service: Microsoft.AzureCosmosDB
- service: Microsoft.ContainerRegistry
- service: Microsoft.KeyVault
- service: Microsoft.Storage
subscription_defaults:
- aliases:
  - default
  location_default: eastus
  subscription_id: 22222222-2222-2222-2222-222222222222
subscriptions:
- subscription_id: 22222222-2222-2222-2222-222222222222
  uamis:
  - location: eastus
    name: msi-id
    resource_group: uami-rg
